"""add match_date to matches

Revision ID: 11fc5a4067ab
Revises: ddf8d6034a77
Create Date: 2026-07-06 12:32:08.589683

"""
from alembic import op
import sqlalchemy as sa


revision = '11fc5a4067ab'
down_revision = 'ddf8d6034a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('match_date')

    # ### end Alembic commands ###
