"""add match_source_keys

Revision ID: c8de4107249e
Revises: 11fc5a4067ab
Create Date: 2026-07-06 12:43:23.009377

"""
from alembic import op
import sqlalchemy as sa


revision = 'c8de4107249e'
down_revision = '11fc5a4067ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_source_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key')
    )
    with op.batch_alter_table('match_source_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_source_keys_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_source_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_source_keys_match_id'))

    op.drop_table('match_source_keys')
    # ### end Alembic commands ###
